---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
 
  # Create a VM from a template
  - name: create the VM
    vmware_guest:
      hostname: '10.51.27.203'
      username: pedrov@network.ctbc
      password: '{{ vsphere_password }}'
      validate_certs: no
      esxi_hostname: vmblade01.network.ctbc
      datacenter: ula_corp
      folder: 'Portal de Clientes PRD'
      name: 'testepedrao'
      state: poweredon
      guest_id: rhel7_64Guest
      disk:
      - size_gb: 30
        type: thin
        datastore: 'DATA_HIT_05-2MB'
      networks:
      - name: 'v66_PortalClientes_Prd'
        ip: '10.51.52.34'
        netmask: 255.255.255.192
        gateway: 10.51.52.1
        dns_servers:
        - 10.32.8.172
        - 10.32.10.125
      - name: 'v66_PortalClientes_Prd'
        ip: '192.168.0.1'
        netmask: 255.255.255.0
      hardware:
        memory_mb: 2048
        num_cpus: 2
      customization:
        dns_servers:
        - 10.32.8.172
        - 10.32.10.125
        domain : network.ctbc
        hostname: 'testepedrao'
      template: 'Template_CentOS-7'
